### ISSUE TITLE
Cannot Read CSV files in Universal Windows Platform Application

### ISSUE THREAD

**Issue by murrayLuke** [cureos/accord#17]
Is there any way to open up CSV files using accord?

In the documentation for accord.io there is a [constructor](http://accord-framework.net/docs/html/M_Accord_IO_CsvReader__ctor_4.htm) for the CsvReader class which takes a string path. But this constructor doesn't seem to exist in the portable version of the accord framework.

Since every other constructor uses a TextReader I have to get a text reader using the following code

```           
using (var fileStream = File.OpenText(path)) {
    using (var csvReader = new CsvReader(fileStream))
```

Unfortunately this causes errors since the type 'File' exists in both Shim version 2.0 as well as System.IO.FileSystem, Version 4.0.1.0

## Steps to Reproduce

Create a new windows 10 project using the UWP template in visual studio. Install portable.accord.io using nuget.

Try to read a file using the CsvReader

```
using (var fileStream = File.OpenText(path)) {
    using (var csvReader = new CsvReader(fileStream))
      ...

```

**Comment by murrayLuke** [comment]
Fixed this by installing the shim package explicitly through nuget.

**Comment by anders9ustafsson** [comment]
Glad to hear you solved the problem, @murrayLuke !
