### ISSUE TITLE
New format Harr Cascade Classifiers

### ISSUE THREAD

**Issue by DRybochkin** [cureos/accord#5]
Hello anyone,
When you are planning to add support for the new format haar cascade classifiers?

Thanks in advance
Dmitry

**Comment by cesarsouza** [comment]
Hello Dmitry,

Actually, I just became aware of this new format today. I didn't have any plans to support it, but I can see if it is going to take much effort. However, you can also use the previous classifiers, as they seem to have worked fine for the past years. Do you think you specifically need to support the newest classifier definitions in the new format in your particular application?

By the way, perhaps we could continue the discussion at the Accord.NET boards as well, as this is not specifically related to cureos.

Regards,
Cesar

**Comment by DRybochkin** [comment]
Hi Cesar,
It would be great to be able to use both old and new format of classifiers.
Let's move the discussion in Accord.NET boards.

Dmitry.

**Comment by DRybochkin** [comment]
Please, create new discussion and send me link.

**Comment by cesarsouza** [comment]
I started a discussion at https://groups.google.com/forum/#!topic/accord-net/yoPT-Zjmhuw

**Comment by DRybochkin** [comment]
Thanks a lot
