### ISSUE TITLE
Missing versioning for portable Accord.Vision

### ISSUE THREAD

**Issue by jagbarrameda** [cureos/accord#7]
It seems that portable version of project _Accord.Vision_ is missing version info. I checked and all the other projects have a link to _\Accord.Core\Properties\VersionInfo.cs_. Is this a intentional or a mistake? Best regards.

**Comment by anders9ustafsson** [comment]
Very observant, you are absolutely right! A silly oversight from my side. I'll fix this as soon as possible.

Many thanks for reporting, @jagbarrameda !
Anders @ Cureos

**Comment by jagbarrameda** [comment]
Your welcome. I actually run into problems when trying to load the assembly using reflection, the info was missing, that's when I noticed it.
Thank you for your work with this project, I'm using it for my studies. 
Excellent work!
