### ISSUE TITLE
Problems to port it to Windows Phone 8

### ISSUE THREAD

**Issue by hrvoje-milkovic** [cureos/accord#8]
Could you help me to port the library to WP8. I need it for a project at my Faculty. Thank your very much.
Hrvoje Milković

**Comment by anders9ustafsson** [comment]
Dear @hrvoje-milkovic,

I think the easiest approach for you is to clone the [accord-samples](https://github.com/cureos/accord-samples) repository. In that repository, there are two WP8 applications that will illustrate how to set up your own project. All the PCL _Shim_, _AForge_ and _Accord_ assemblies that you will need is also available in the _Externals_ sub-folder of the _accord-samples_ repository.

Best of luck!
Anders @ Cureos
